### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by cpu150** [GeekFunkLabs/squishbox#12]
Since the last change there is an error in the script execution line 445.
Two `do`  are following:
d=\$installdir; while [ "\$d" != "" ]; **DO** chown \$USER $d; **DO** chmod g+x \$d; d=\${d%/*}; done

https://github.com/GeekFunkLabs/squishbox/blame/a73e25920bd807d8a4a7af55fa03befc69b36f39/squishbox-install.bash#L445

`bash: line 445: syntax error near unexpected token `do'
bash: line 445: `    d=$installdir; while [ "$d" != "" ]; do chown $USER $d; do chmod g+x $d; d=${d%/*}; done'`

**Comment by albedozero** [comment]
Thanks for the catch - one too many `do`s
