### ISSUE TITLE
lcdsplash.service fails 

### ISSUE THREAD

**Issue by joshuaryoung** [GeekFunkLabs/squishbox#13]
DIY kit. Everything works great but no splash screen and the console logs mention this failure and systemctl shows that it has something to do with the GPIO pins. Something about “pull” not being defined.

- Pi 4 8gb
- Latest PiOS lite

**Comment by albedozero** [comment]
This might have something to do with rpi-lgpio not getting installed properly, which was supposed to be fixed by #3. The exact error would be helpful - could you share the output of the command `journalctl -u lcdsplash.service -n 20 --no-pager`?

**Comment by albedozero** [comment]
Fixed by #14 thanks

**Comment by joshuaryoung** [comment]
Confirmed working now! Sorry for not following up with the logs!
