### ISSUE TITLE
Audio muted on 1/4" jacks, LCD and buttons are working

### ISSUE THREAD

**Issue by albedozero** [GeekFunkLabs/squishbox#4]
_Originally posted by @unRARed in https://github.com/GeekFunkLabs/squishbox/issues/1#issuecomment-2067041318_

> My latest attempt was installing on my older Pi 3B on the "recommended" 32bit image. The OS and script installed without issue and booted directly to the interface. Both the Rotary, Button and LED also seem to function flawlessly, but there's still no sound out of the 1/4" jacks. I tried disabling all the other sound devices, too.
> 
> Is it possible the script is assuming the user is `pi`? In all cases, I've preconfigured the Pi image with a custom username and password, but I've confirmed my user is in the audio group.
> 
> The closest thing I've achieved sound-wise is plugging in a little pocket guitar amp. There's a noise on the line until I run `./squishbox.py`. At this point the noise is gone. When I terminate the process, the noise returns. Is it possible the wiring diagram is wrong in the installation PDF for the 1/4" jacks?
>

**Comment by albedozero** [comment]
I don't think the issue could be installing with a user other that `pi` - I've tested this many times with no issues. I think the quickest way to isolate whether it's a wiring problem would be to connect some headphones to the Pi's on-board audio jack and change the following line in SquishBox/fluidpatcherconf.yaml:

```yaml
  audio.alsa.device: sndrpihifiberry
```

to

```yaml
  audio.alsa.device: Headphones
```

The wiring guide in the latest documentation, [linked from this repo](https://geekfunklabs.github.io/squishbox/assembly.html#hardware), is correct.

**Comment by albedozero** [comment]
Any developments on this issue @unRARed?

**Comment by unRARed** [comment]
I’m slammed with projects lately so unfortunately no, I haven’t had a chance to. I double checked the wiring, and I can’t see an issue there though. You can privately close this for now. Not sure when I’ll be able to revisit. Thanks for the support!
