### ISSUE TITLE
Fluidsynth: Failed to set thread to high priority

### ISSUE THREAD

**Issue by cpu150** [GeekFunkLabs/squishbox#6]
# Description
After a fresh install and reboot the service starts with the log `fluidsynth: warning: Failed to set thread to high priority`

<img width="898" alt="Logs - Failed to set thread priority" src="https://github.com/GeekFunkLabs/squishbox/assets/13674265/7d7c731e-1463-4bd1-97b7-70ddc68f9eff">

# Steps to reproduce
1. Flash `Raspberry Pi Os Lite (64-bit)` (Debian Bookworm - no desktop environment)
2. Update system: `sudo apt update ; sudo apt -y upgrade`
3. Install SquishBox as `Naked Raspberry Pi Synth`
4. Reboot
5. Watch status: `systemctl status squishbox`

Result: The log `fluidsynth: warning: Failed to set thread to high priority` appears
Expected: No failure

# Setup
Raspberry Pi Zero 2W:
- Operating System: Debian GNU/Linux 12 (bookworm)
- Kernel: Linux 6.6.28+rpt-rpi-v8
- Architecture: arm64

Squishbox:
- Naked Raspberry Pi Synth
- USB audio output - card 0: Audio [Hi-Res Audio], device 0: USB Audio [USB Audio]

**Comment by cpu150** [comment]
# Proposed fix
Give the service the right to change the thread priority by adding in `squishbox-install.bash` script under the `[Service]` section:
`LimitMEMLOCK=infinity
LimitRTPRIO=90`

@albedozero I have a local branch with the fix but can't push it (I don't have the rights). I can push it and create a pull request if it helps

**Comment by albedozero** [comment]
Fantastic. I'd thought this was unfixable and the warnings just had to be ignored, but this solves it and is [corroborated in the forums](https://forums.raspberrypi.com/viewtopic.php?t=211327) as well. I'd be happy to merge a pull request but this one was quick so I just did it with #8. Thanks for contributing!
